config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'shifts#index'
	resources :shifts
	resources :roles
	post "shifts/reply" => "shifts#reply"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :user_roles
	has_many :user, through: :user_roles
end

app/models/shift.rb
class Shift < ApplicationRecord
	has_many :user_shifts
	has_many :users, through: :user_shifts

	after_save :broadcast

	def broadcast
		if self.is_reschedulable?
			@twilio_number = ENV['TWILIO_NUMBER']
			@client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
			@users_numbers = User.all
			shift = self.id
			@users_numbers.each do |user|
				@message = "Hi #{user.email}. A new shift has become available. Reply yes #{shift} if you would like to take this shift"
				unless user.phone.nil?
					message = @client.account.messages.create(
							:from => @twilio_number,
							:to => user.phone,
							:body => @message,
					)
					puts message.to
				end
			end
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :user_roles
	has_many :roles, through: :user_roles
	has_many :user_shifts
	has_many :shifts, through: :user_shifts

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/user_shift.rb
class UserShift < ApplicationRecord
  belongs_to :user
  belongs_to :shift

  after_save :notify
  # after_update :notify

  # @@REMINDER_TIME = 30.minutes # minutes before appointment


  def notify
	  @twilio_number = ENV['TWILIO_NUMBER']
	  @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
	  start = ((self.shift.start).localtime).strftime("%I:%M%p on %b. %d, %Y")
	  finish = ((self.shift.end).localtime).strftime("%I:%M%p on %b. %d, %Y")
	  shift = self.shift.id
	  @phone = self.user.phone
	  message = "Hi #{self.user.email}. You have a new shift from #{start} to #{finish}. If for any reason you cannot make it please reply NO #{shift} to this text"
	  message = @client.account.messages.create(
			  :from => @twilio_number,
			  :to => @phone,
			  :body => message,
	  )
		  puts message.to
  end

  # def when_to_run
	 #  time - @@REMINDER_TIME
  # end

  # handle_asynchronously :reminder, :run_at => Proc.new { |i| i.when_to_run }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	def index
		@roles = Role.all
	end
	def new
		@role = Role.new
	end

	def show
		@role = Role.find(params[:id])
	end

	def create
		role = Role.create!(role_params)
		redirect_to role_path(role)
	end

	private

	def role_params
		params.require(:role).permit(:name)
	end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
	before_action :authenticate_user!, except: [:reply]
	skip_before_filter :verify_authenticity_token, only: [:reply]

	def reply
		message_body = params["Body"].downcase
		from_number = params["From"]
		boot_twilio
		if message_body.include?("no")
			shift_id = message_body.scan(/\d+/)
			shift = shift_id[0].to_i
			user = User.find_by(phone: from_number)
			change_shift = user.shifts.find_by(id: shift)
			change_shift.is_reschedulable = true
			change_shift.save
			destroy_shift = user.user_shifts.where(shift_id: shift)
			destroy_shift[0].destroy
			sms = @client.messages.create(
					from: ENV["TWILIO_NUMBER"],
					to: from_number,
					body: "We have received your message, your shift has successfully been cancelled"
			)
		elsif message_body.include?("yes")
			shift_id = message_body.scan(/\d+/)
			shift = shift_id[0].to_i
			user = User.find_by(phone: from_number)
			change_shift = Shift.find_by(id: shift)
			if change_shift.is_reschedulable?
				change_shift.users << user
				change_shift.is_reschedulable = false
				change_shift.save
			else
				sms = @client.messages.create(
						from: ENV["TWILIO_NUMBER"],
						to: from_number,
						body: "The shift has already been taken"
				)
			end
		else
	    sms = @client.messages.create(
			    from: ENV["TWILIO_NUMBER"],
			    to: from_number,
			    body: "Sorry your response was invalid. If you were trying to cancel a shift, please call you line manager for assistance "
	    )
		end


	end

	def index
		@shifts = Shift.all
	end


	def new
		@shift = Shift.new
	end

	def edit
		@shift = Shift.find(params[:id])
	end

	def show
		@shift = Shift.find(params[:id])
		# @members = User.all
	end

	def create
		shift = Shift.create(shift_params)
		redirect_to shift_path(shift)
	end

	def update
		@shift = Shift.find(params[:id])
		@shift.update(shift_params)
	end

	def destroy
		@shift = Shift.find(params[:id])
		@shift.destroy
		redirect_to root_path
	end


	private

	def boot_twilio
		@client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
	end

	def shift_params
		params.require(:shift).permit(:date, :start, :end, user_ids: [])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EScheduler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
  <div class="ui pointing menu">
	  <%= link_to "Home", shifts_path, class: "item" %>
	  <%= link_to "Create shift", new_shift_path, class: "item" %>
	  <div class="right menu">
		  <div class="item">
			  <div class="ui transparent icon input">
				  <input type="text" placeholder="Search...">
				  <i class="search link icon"></i>
			  </div>
		  </div>
	  </div>
  </div>
    <%= yield %>
  </body>
</html>

app/views/roles/index.html.erb
<div class="ui container">
	<% @roles.each do |role| %>
			<div class="ui segment">
				<%=link_to role.name %><br>
			</div>
	<% end %>
</div>

app/views/roles/new.html.erb
<div class="ui container">
	<div class="ui form">
		<%= form_for @role do |f| %>
				<%= f.label :role %><br><br>
				<%= f.text_field :name %><br><br>
				<%= f.submit class: "ui teal button" %>
		<% end %>
	</div>
</div>

app/views/roles/show.html.erb
<div class="ui container">
	<div class="ui segment">
		<%= link_to @role.name %>
	</div>
</div>

app/views/shifts/edit.html.erb
<div class="ui container">
	<div class="ui grid">
		<div class="six wide column">
			<div class="ui form">
				<%= form_for @shift do |f| %>
						<%= f.date_field :date %><br><br>
						<%= f.time_field :start %><br><br>
						<%= f.time_field :end%><br>
						<%= f.collection_check_boxes :user_ids, User.all, :id, :email, :multiple => true do |b| %><br>
								<%= b.label class:"label-checkbox" do%>
										<%=b.check_box + " " + b.text%>
								<%end%>
						<% end %>
						<br>
						<br>
						<%= f.submit class: "ui teal button" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/shifts/index.html.erb
<div class="ui container">
	<div class="row">
			<h1>Welcome to Scheduler </h1>
			<%= link_to "New Shift", new_shift_path, class: "ui teal button" %>
	</div>
	<table class="ui fixed single line celled teal table">
		<thead>
			<tr>
				<th>Date</th>
				<th>Start</th>
				<th>Finish</th>
				<th>Head Count</th>
				<th>Edit</th>
			</tr>
		</thead>
		<tbody>
		<% @shifts.each do |shift| %>
		<tr>
			<td><%= shift.date.strftime("%b. %d, %Y") %></td>
			<td><%= shift.start.strftime("%I:%M%p") %></td>
			<td><%= shift.end.strftime("%I:%M%p") %></td>
			<td><%= shift.user_shifts.count %></td>
			<td class="selectable"><%= link_to "Edit This", shift_path(shift) %></td>
		</tr>
		<% end %>
		</tbody>
		</table>
</div>

app/views/shifts/new.html.erb
<div class="ui container">
	<div class="ui grid">
		<div class="six wide column">
			<div class="ui form">
				<%= form_for @shift do |f| %>
						<%= f.date_field :date %><br><br>
						<%= f.time_field :start %><br><br>
						<%= f.time_field :end%><br>
						<%= f.collection_check_boxes :user_ids, User.all, :id, :email, :multiple => true do |b| %><br>
								<%= b.label class:"label-checkbox" do%>
										<%=b.check_box + " " + b.text%>
								<%end%>
								<% end %>
						<br>
						<br>
						<%= f.submit class: "ui teal button" %>
				<% end %>
			</div>
		</div>
	</div>
</div>
x

app/views/shifts/show.html.erb
<div class="ui container">
	Date: <%= @shift.date %><br>
	Shift start time: <%= @shift.start %><br>
	Shift end time: <%= @shift.end %><br>
	Current Attendees: <%= @shift.user_shifts.count %><br><br>
	<%= link_to "Delete Shift", shift_path, method: :delete, class: "ui red button", data: {confirm: "Are you sure?"} %>
	<%= link_to "Alter Shift", edit_shift_path, class: "ui green button" %>
</div>